collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5764411
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#0D0C0A'
    - '#A39B90'
    - '#6D665C'
    - '#3B3731'
  lightness: 0.4972015
layout_spectrum: 0.6616541
name: Sideradis
