collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.4843358
  lightness: 0
  brandColors:
    - '#040304'
    - '#4B4239'
    - '#868177'
    - '#E1DED9'
    - '#C5BDB5'
  rhythmicContrast: 0
typography_spectrum: 0.5764411
layout_spectrum: 0.9160401
name: Sideradis
