favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 0
  brandColors:
    - '#0D0C0A'
    - '#A39B90'
    - '#6D665C'
    - '#3B3731'
  lightness: 1
typography_spectrum: 0.56406
layout_spectrum: 0.3972431
cta:
  bucket: null
  version: null
  domain: null
name: Sideradis
