collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5764411
color:
  saturation: 0.4814251
  brandStrength: 0.924812
  rhythmicContrast: 0.9976538
  brandColors:
    - '#040304'
    - '#4B4239'
    - '#868177'
    - '#E1DED9'
    - '#C5BDB5'
  lightness: 0.06456656
layout_spectrum: 0.8941103
name: Sideradis
